### ISSUE TITLE
Несовпадение размеров иконок экспертов (768)

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#10]
![image](https://user-images.githubusercontent.com/101792032/175999706-33df343a-029d-45ae-8338-a5046d8b0fe9.png)

Там должно быть 132 пикселя (в макете 131, но лучше делать четные номера, а еще лучше уточнять у дизайнера, опять же)

**Comment by VKNagibin** [comment]
Пиксель пёрфект и всё пёрфект
