### ISSUE TITLE
Несовпадение верстки (768)

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#11]
![image](https://user-images.githubusercontent.com/101792032/176000085-8aaa5093-abf1-44bc-b8cc-1c5fd5bb1aea.png)

Чет не сходится

![image](https://user-images.githubusercontent.com/101792032/176000134-93e8de8f-1971-4932-ae78-2d2cbad6d6a0.png)

**Comment by VKNagibin** [comment]
Исправил
