### ISSUE TITLE
Ссылки выглядят некорректно

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#13]
![image](https://user-images.githubusercontent.com/101792032/176000510-a15bc410-0e43-4df6-8643-a1cb52e6f804.png)

А по факту 

![image](https://user-images.githubusercontent.com/101792032/176000532-532dd6f1-d49c-437b-a397-11076bcb4c78.png)

И логотип где-то не там

**Comment by VKNagibin** [comment]
Исправил. Теперь как на макете
