### ISSUE TITLE
Определись с неймингами

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#16]
![image](https://user-images.githubusercontent.com/101792032/176002684-65661705-3e19-49f4-95d0-50ba730f714a.png)

Продолжая тему чистого кода, если тебе не сказали какой стиль написания используется, выбери один и старайся его придерживаться.

На фронте чаще всего именно в таком порядке:
1. camelCase - каждоеСловоСБольшойБуквы
2. kebab-case - каждое-слово-через-тире

Остальное практически не встречал

![image](https://user-images.githubusercontent.com/101792032/176003182-ff9e02bf-113b-4ae9-baf9-391e61107a04.png)

PascalCamelCase для классов и интерфейсов еще годится, но это тот же верблюд

**Comment by mordvinian** [comment]
MACRO_CASE для всяких констант еще можно юзать, чтобы без магических чисел в коде.

`const BACKEND_ROOT_URL = 'https://your.backend.com/api/v2'`

**Comment by VKNagibin** [comment]
Все файлы в CamelCase теперь
