### ISSUE TITLE
Пустые элементы в верстке обычно являются плохой практикой

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#18]
![image](https://user-images.githubusercontent.com/101792032/176109545-a6a68fb1-5b1b-4039-9a66-fb298a1ca813.png)

Выглядит как костыль. Что делает этот див?

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/176116084-dd7c3fc1-5788-4f0e-9254-ec9bc8035d78.png)

Аналогичный момент, какая-то непонятная х

**Comment by mordvinian** [comment]
Если уж совсем никак без таких штук, то можно внуть засунуть коммент, что оно делает, потому что иначе это выглядит как просто какая-то магическая конструкция, без которой все сломается (сломается ведь?)

Я бы не рискнул его удалять просто так, потому что кажется будто этот див что-то делает.

**Comment by VKNagibin** [comment]
Один удалил, за другой в комментарии пояснил)

**Comment by mordvinian** [comment]
Расскажи пожалуйста как он работает как будешь в офисе, интересно)

**Comment by VKNagibin** [comment]
Закрываю issue, в офисе пояснил за div)
