### ISSUE TITLE
Поехала верстка в шапке

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#2]
![image](https://user-images.githubusercontent.com/101792032/175995078-0ceaf464-f52f-4b84-a6d5-3ef293781cc8.png)

В каком-то другом месте дизайнер скорее всего забил бы на поехавший перенос слова, но явно не на первом экране.

Попробуй nbsp добавить https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D1%80%D0%B0%D0%B7%D1%80%D1%8B%D0%B2%D0%BD%D1%8B%D0%B9_%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB

**Comment by VKNagibin** [comment]
Я в span обернул часть строки и с определённого размера display: block ему дал. Одним словом - исправил
