### ISSUE TITLE
Вероятно избыточная вложенность

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#21]
![image](https://user-images.githubusercontent.com/101792032/176115506-d2de246f-370a-4059-8f0f-d0b4d02563e7.png)

Скорее всего не обязательно вкладывать картинку в див.

Попробуй отрефакторить с помощью object-fit, object-pozition и display: block кинуть на img.

**Comment by mordvinian** [comment]
Аналогично по всем остальным подобным конструкциям.

Более того, из-за того что так вкладываешь появляется секретная особенность inline-block

![image](https://user-images.githubusercontent.com/101792032/176115924-f95690dd-f3a7-407c-927f-31c0468b6a82.png)

Видишь отступ снизу? Это не маржин и не паддинг, это секрет)

Так работает inline-block

**Comment by VKNagibin** [comment]
Очень полезная инфа, много косяков помогла исправить, благодарю
