### ISSUE TITLE
Излишняя вложенность

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#23]
![image](https://user-images.githubusercontent.com/101792032/176117459-e349a14c-3c0d-4d79-bcf8-be0ce4fe1178.png)

Тэг, внутри которого лежит только один тэг - это признак что происходит какая-то х

Тут можно избавиться от div.container ?

**Comment by mordvinian** [comment]
Может перенести .container на section?

**Comment by VKNagibin** [comment]
Согласен, но переносить не стал, т.к. вёрстке стало плохо после рефакторинга

**Comment by mordvinian** [comment]
Пссс, я подсказываю

![image](https://user-images.githubusercontent.com/101792032/176496712-ebfa2999-3c9b-4d86-a798-2258bf1fd890.png)

**Comment by mordvinian** [comment]
Каждый элемент в DOM дереве это достаточно громоздкий объект, просчет которого занимает ощутимое количество времени.

Реактивные фреймворки типа react или vue для того и используют, чтобы манипулировать не DOM деревом, а чем-то более легким, например, JavaScript объектами. А реальный DOM трогать как можно меньше.

Если мы можем исключить какой-то элемент из верстки без потерь, нам следует это делать.

**Comment by mordvinian** [comment]
Если мы выкинем лишние дивы, то:

- Страница будет грузиться быстрее т.к. меньше данных
- Страница будет рисоваться браузером быстрее по той же причине
- Страница будет изменяться быстрее
- Страница будет занимать меньше памяти

Главное, чтобы выкидывание дивов не снижало качество, и не усложняло поддержку

**Comment by VKNagibin** [comment]
Спасибо за инфу. Исправил
