### ISSUE TITLE
Осторожнее с BR

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#25]
![image](https://user-images.githubusercontent.com/101792032/176119513-2afa813e-84c9-4379-8676-c432c7f19b14.png)

Обычно брки долго живут только в статике. Как только появляются медиа-запросы приходится рефакторить.

Здесь это, вероятно, уместно.

**Comment by VKNagibin** [comment]
Понял, в топку br -ы!
