### ISSUE TITLE
skills-list__item лучше бы иметь паддинги

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#27]
![image](https://user-images.githubusercontent.com/101792032/176123285-05d1855e-7c14-4a8c-8020-e3abff85922b.png)

Убрал маржин с текста и все сломалось.

Тут лучше на сам li повесить padding со всех сторон. 
Тогда у картинки как раз останется только маржин-боттом

**Comment by VKNagibin** [comment]
Тогда вёрстка ломается. Сейчас текст расположен как на макете, а с паддингами он скучивается.

**Comment by VKNagibin** [comment]
Переделал на паддинги, можешь мной гордиться

**Comment by mordvinian** [comment]
Красавчик! Решение отличное
