### ISSUE TITLE
Использование div вместо img

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#28]
![image](https://user-images.githubusercontent.com/101792032/176176649-7d036cde-e6de-402a-886d-7b445f39003f.png)

Почему тут div? Почему нельзя использовать img?

**Comment by VKNagibin** [comment]
Я ставил изображения в качестве background для div. Так легче управлять размерами и стилизацией блока, как мне кажется

**Comment by mordvinian** [comment]
Почитай пожалуйста:

https://developer.mozilla.org/ru/docs/Web/CSS/object-position
https://developer.mozilla.org/ru/docs/Web/CSS/object-fit

Как прочтешь напиши, я тебе немного подскажу и сделаем чтобы были img

**Comment by VKNagibin** [comment]
Готово!
