### ISSUE TITLE
Несовпадают размеры

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#29]
![image](https://user-images.githubusercontent.com/101792032/176177237-4e1b7c4c-b98c-41ed-94a2-e2f916b6fad6.png)

В макете по-другому

![image](https://user-images.githubusercontent.com/101792032/176177325-57f9b2f1-7210-44e5-a951-7b6fd456ab6f.png)

**Comment by VKNagibin** [comment]
Исправлено
