### ISSUE TITLE
BR - зло

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#30]
![image](https://user-images.githubusercontent.com/101792032/176178103-251ff15a-3c88-404b-af17-a0016d2e68e7.png)

Одна бр это плохо, а две бр это П

Тут надо как-то по-другому разделить. На параграфы, например.

**Comment by VKNagibin** [comment]
Поборолся со злом. Победил, кстати

**Comment by mordvinian** [comment]
Красавчик, так его! Перо ему в бок нах

Стало чище
