### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#31]
![image](https://user-images.githubusercontent.com/101792032/176178508-a8253794-1284-4c53-8d8b-593948e02182.png)

Не сходится с макетом.

тэг A внутри Button.

Бр норм, можно оставить

**Comment by VKNagibin** [comment]
Кнопка теперь в виде ссылки. Переверстал всё

**Comment by mordvinian** [comment]
Супер, молодец!
