### ISSUE TITLE
Ссылки в подвале

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#32]
![image](https://user-images.githubusercontent.com/101792032/176178970-bc934482-91c5-440e-9a9e-017ec1d1c901.png)

tel: здорово,
для почты какая-то х.

По-моему там mailto:partners@worksolutions.ru должно быть

**Comment by VKNagibin** [comment]
Заменил ссылку

**Comment by mordvinian** [comment]
Супер!
