### ISSUE TITLE
Маржины и текст

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#33]
Просто на заметку, исправлять не надо, и так хорошо сделано.

![image](https://user-images.githubusercontent.com/101792032/176493716-a62cb46a-2449-44fc-b030-353cf926bbc3.png)

23 пикселя выглядит как магическое число. Когда у тебя маржин как-то связан с текстом, то лучше использовать величины, зависящие от размера текста. 1.5rem так и говорит, что margin тут в полторы строчки. Это лучше чем магические 23 пикселя.

НО! Сделано хорошо, переделывать НЕ нужно, просто на заметку тебе пингую, что так тоже можно.

**Comment by mordvinian** [comment]
Закрывай как ознакомишься

**Comment by VKNagibin** [comment]
Ага, понял, спасибо
