### ISSUE TITLE
Картинка неадекватно скейлится при изменении ширины

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#4]
![image](https://user-images.githubusercontent.com/101792032/175995839-429f0694-de50-4cfd-88af-e565d2ed64f0.png)
![image](https://user-images.githubusercontent.com/101792032/175995897-716ff9de-4a5d-444f-9d42-9b6b2fe02130.png)

Сравни две картинки. Видишь пропорции меняются? Если попробовать двигать ширину туда-сюда она вообще как желе прыгает, прикольно)

Так точно не годится, потому что на промежуточных разрешениях выглядит плохо. Попробуй это:

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
https://developer.mozilla.org/ru/docs/Web/CSS/object-position

**Comment by VKNagibin** [comment]
Сделал картинку статичной, вроде неплохо выглядит
