### ISSUE TITLE
Неправильно проанализировано задание

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutionsTemplate#9]
Вот пример верстки 

![image](https://user-images.githubusercontent.com/101792032/175998415-1b8e5b74-aac5-4fa4-a9bd-6a29266fa955.png)

Вот макет

![image](https://user-images.githubusercontent.com/101792032/175998449-2457521d-98d3-478a-a25a-fea27dfa647a.png)

Разрешения немного разные, поэтому тут ошибка в анализе задание.

Я думаю тут все же неуместно так растягивать логотипы, по идеи они должны оставаться в заданных размерах
![image](https://user-images.githubusercontent.com/101792032/175998698-e97824c2-a757-4b6a-aeb4-d614a4534ba1.png)

Посмотри пожалуйста на плакаты в коридоре где обеденная зона, там прям поэтапно написано.
В идеале, должно было быть так:

1. Смотришь макет на ширинах a-b
2. Представляешь как должна выглядеть верстка на **промежуточных ширинах между** a-b. Это и есть анализ техзадания.
3. Непонятные, неточные, скользкие, моменты - уточняешь с постановщиком, дизайнером, или другим ответственным лицом.  Это в будущем тебе очень поможет подстраховаться и оставит о тебе хорошее впечатление. Лучше задать глупый вопрос, чем сделать и переделывать)
4. Как только тебе точно понятно, что делать - делаешь. 

Но это так, советы)

Сделай чтоб не скейлилось пожалуйста, а совет на будущее отметь)

**Comment by VKNagibin** [comment]
Да, много ошибок из-за спешки и некудышного анализа макета, впредь буду внимательнее
